package com.guojijian.pethospital.settings.mapper;

import com.guojijian.pethospital.settings.pojo.Employee;
import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    int deleteByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    Employee selectByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    int updateByPrimaryKey(Employee record);

    /**
     * 根据账号和密码查询员工
     */
    Employee selectEmployeeByActAndPwd(Employee employee);
}