package com.guojijian.pethospital.settings.mapper;

import com.guojijian.pethospital.settings.pojo.PetOwner;
import java.util.List;
import java.util.Map;

public interface PetOwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_pet_owner
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_pet_owner
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    int insert(PetOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_pet_owner
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    PetOwner selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_pet_owner
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    List<PetOwner> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_pet_owner
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    int updateByPrimaryKey(PetOwner record);

    /**
     * 根据用户id和password查询用户
     */
    PetOwner selectPetOwnerByActAndPwd(PetOwner petOwner);
}