package com.guojijian.pethospital.settings.pojo;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.eid
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_user_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_password
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String ePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_allow_ips
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eAllowIps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_email
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_expire_time
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eExpireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_lock_state
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eLockState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_gender
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_age
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_position
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String ePosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_department
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String eDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.e_phone
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String ePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_employee.grade
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String grade;

    private String odType;

    public String getOdType() {
        return odType;
    }

    public void setOdType(String odType) {
        this.odType = odType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.eid
     *
     * @return the value of tbl_employee.eid
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.eid
     *
     * @param eid the value for tbl_employee.eid
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_user_name
     *
     * @return the value of tbl_employee.e_user_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteUserName() {
        return eUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_user_name
     *
     * @param eUserName the value for tbl_employee.e_user_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteUserName(String eUserName) {
        this.eUserName = eUserName == null ? null : eUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_password
     *
     * @return the value of tbl_employee.e_password
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getePassword() {
        return ePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_password
     *
     * @param ePassword the value for tbl_employee.e_password
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setePassword(String ePassword) {
        this.ePassword = ePassword == null ? null : ePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_allow_ips
     *
     * @return the value of tbl_employee.e_allow_ips
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteAllowIps() {
        return eAllowIps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_allow_ips
     *
     * @param eAllowIps the value for tbl_employee.e_allow_ips
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteAllowIps(String eAllowIps) {
        this.eAllowIps = eAllowIps == null ? null : eAllowIps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_email
     *
     * @return the value of tbl_employee.e_email
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteEmail() {
        return eEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_email
     *
     * @param eEmail the value for tbl_employee.e_email
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteEmail(String eEmail) {
        this.eEmail = eEmail == null ? null : eEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_expire_time
     *
     * @return the value of tbl_employee.e_expire_time
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteExpireTime() {
        return eExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_expire_time
     *
     * @param eExpireTime the value for tbl_employee.e_expire_time
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteExpireTime(String eExpireTime) {
        this.eExpireTime = eExpireTime == null ? null : eExpireTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_lock_state
     *
     * @return the value of tbl_employee.e_lock_state
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteLockState() {
        return eLockState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_lock_state
     *
     * @param eLockState the value for tbl_employee.e_lock_state
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteLockState(String eLockState) {
        this.eLockState = eLockState == null ? null : eLockState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_name
     *
     * @return the value of tbl_employee.e_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_name
     *
     * @param eName the value for tbl_employee.e_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_gender
     *
     * @return the value of tbl_employee.e_gender
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteGender() {
        return eGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_gender
     *
     * @param eGender the value for tbl_employee.e_gender
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteGender(String eGender) {
        this.eGender = eGender == null ? null : eGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_age
     *
     * @return the value of tbl_employee.e_age
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteAge() {
        return eAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_age
     *
     * @param eAge the value for tbl_employee.e_age
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteAge(String eAge) {
        this.eAge = eAge == null ? null : eAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_position
     *
     * @return the value of tbl_employee.e_position
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getePosition() {
        return ePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_position
     *
     * @param ePosition the value for tbl_employee.e_position
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setePosition(String ePosition) {
        this.ePosition = ePosition == null ? null : ePosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_department
     *
     * @return the value of tbl_employee.e_department
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String geteDepartment() {
        return eDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_department
     *
     * @param eDepartment the value for tbl_employee.e_department
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void seteDepartment(String eDepartment) {
        this.eDepartment = eDepartment == null ? null : eDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.e_phone
     *
     * @return the value of tbl_employee.e_phone
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getePhone() {
        return ePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.e_phone
     *
     * @param ePhone the value for tbl_employee.e_phone
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setePhone(String ePhone) {
        this.ePhone = ePhone == null ? null : ePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.grade
     *
     * @return the value of tbl_employee.grade
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.grade
     *
     * @param grade the value for tbl_employee.grade
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }
}