package com.guojijian.pethospital.settings.pojo;

public class PetOwner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.pid
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_user_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_password
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */

    private String pCall;

    private String pPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_phone
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_email
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pName;

    private String pSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_type
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_breed
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pBreed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_age
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.p_status
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String pStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_pet_owner.grade
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    private String grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.pid
     *
     * @return the value of tbl_pet_owner.pid
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.pid
     *
     * @param pid the value for tbl_pet_owner.pid
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_user_name
     *
     * @return the value of tbl_pet_owner.p_user_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpUserName() {
        return pUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_user_name
     *
     * @param pUserName the value for tbl_pet_owner.p_user_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpUserName(String pUserName) {
        this.pUserName = pUserName == null ? null : pUserName.trim();
    }

    public String getpCall() {
        return pCall;
    }

    public void setpCall(String pCall) {
        this.pCall = pCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_password
     *
     * @return the value of tbl_pet_owner.p_password
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpPassword() {
        return pPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_password
     *
     * @param pPassword the value for tbl_pet_owner.p_password
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpPassword(String pPassword) {
        this.pPassword = pPassword == null ? null : pPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_phone
     *
     * @return the value of tbl_pet_owner.p_phone
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpPhone() {
        return pPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_phone
     *
     * @param pPhone the value for tbl_pet_owner.p_phone
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpPhone(String pPhone) {
        this.pPhone = pPhone == null ? null : pPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_email
     *
     * @return the value of tbl_pet_owner.p_email
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpEmail() {
        return pEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_email
     *
     * @param pEmail the value for tbl_pet_owner.p_email
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpEmail(String pEmail) {
        this.pEmail = pEmail == null ? null : pEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_name
     *
     * @return the value of tbl_pet_owner.p_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_name
     *
     * @param pName the value for tbl_pet_owner.p_name
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    public String getpSex() {
        return pSex;
    }

    public void setpSex(String pSex) {
        this.pSex = pSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_type
     *
     * @return the value of tbl_pet_owner.p_type
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_type
     *
     * @param pType the value for tbl_pet_owner.p_type
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpType(String pType) {
        this.pType = pType == null ? null : pType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_breed
     *
     * @return the value of tbl_pet_owner.p_breed
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpBreed() {
        return pBreed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_breed
     *
     * @param pBreed the value for tbl_pet_owner.p_breed
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpBreed(String pBreed) {
        this.pBreed = pBreed == null ? null : pBreed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_age
     *
     * @return the value of tbl_pet_owner.p_age
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpAge() {
        return pAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_age
     *
     * @param pAge the value for tbl_pet_owner.p_age
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpAge(String pAge) {
        this.pAge = pAge == null ? null : pAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.p_status
     *
     * @return the value of tbl_pet_owner.p_status
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getpStatus() {
        return pStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.p_status
     *
     * @param pStatus the value for tbl_pet_owner.p_status
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setpStatus(String pStatus) {
        this.pStatus = pStatus == null ? null : pStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_pet_owner.grade
     *
     * @return the value of tbl_pet_owner.grade
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_pet_owner.grade
     *
     * @param grade the value for tbl_pet_owner.grade
     *
     * @mbggenerated Fri Feb 03 21:07:12 CST 2023
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }
}